Allow homarus to use faststart for video conversion
Islandora-CLAW/Crayfish pull request #162
Opened 2022-09-08 09:47 UTC by bibliophileaxe

**GitHub Issue**: (link)
https://github.com/Islandora/documentation/issues/2162

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
https://stackoverflow.com/questions/64661989/chrome-video-tag-cant-play-fragmented-mp4-stream
https://gitlab.com/Shinobi-Systems/Shinobi/-/issues/237
https://gitlab.com/Shinobi-Systems/Shinobi/-/issues/66

# What does this Pull Request do?
Replaces the moveflags frag_keyframe+empty_moov with faststart

A brief description of what the intended result of the PR will be and/or what problem it solves.
It allows videos to be played instantly on all browsers. On chrome large fragmented videos take too long to play.

# What's new?

* Remove moveflags frag_keyframe+empty_moov
* Added moveflags faststart
* Converted file is saved as a tempfile - It is not possible to stream output with faststart.
* The response has changed from StreamResponse to BinaryFileResponse

# How should this be tested?

* Ingest a large video file preferably mov and wait for derivative generation. Now try to play this file on chrome. There are multiple 206 partial content network requests and video starts playing after the moov atom for each fragment has been loaded.
* Now try the same with this PR. The video will start playing instantly.

# Additional Notes:
Open to suggestions about alternate solutions but I've searched everywhere and couldn't find anything else that works.

# Interested parties
@Islandora/committers  @Islandora/8-x-committers @adam-vessey @lutaylor @willtp87 @jordandukart

2022-09-08 14:31 UTC, jordandukart requested changes
Some comments on the PR, in general as well the existing set of tests are failing due to the changes here.

2022-09-08 14:31 UTC, jordandukart commented on Homarus/src/Controller/HomarusController.php
> +            return (new BinaryFileResponse(
This breaks some expectations with existing installations or configurations of Islandora. That is, depending on whether someone is using ISLE (Dockerized) or how their Crayfish is configured, it could be very possible that there would be not enough space to allow ffmpeg to run create derivatives. This could also become exasperated if multiple derivatives were being able to be executed per a single instance in parallel.

2022-09-08 14:31 UTC, jordandukart commented on Homarus/src/Controller/HomarusController.php
>          if ($format == "mp4") {
At this point I'm unsure if there's a particular reason that `mp4`s get their own separate flow of logic with arguments where as [Houdini](https://github.com/Islandora/Crayfish/blob/2.x/Houdini/src/Controller/HoudiniController.php#L115) allows for the header to pass through everything that's to be ran.

2022-09-08 14:31 UTC, jordandukart commented on Homarus/src/Controller/HomarusController.php
> +            ))->deleteFileAfterSend(true);
In general in terms of maintaining backwards compatibility we'd likely want to keep the existing behavior and allow a deviation here to be opt-in. Introducing new config in: https://github.com/Islandora/Crayfish/blob/2.x/Homarus/cfg/config.example.yaml and passing through to the [controller](https://github.com/Islandora/Crayfish/blob/277f48af8fca1656ca3e777c5d70e4639770d854/Homarus/src/app.php#L16-L24) could be a way to accomplish this.

Alternatively, given some of the things being highlighted here the introduction of a completely separate route may make more sense given the potential level of changes that may be getting introduced here.

2022-09-08 15:57 UTC, whikloj commented on Homarus/src/Controller/HomarusController.php
> +            return (new BinaryFileResponse(
This is also my immediate concern, while I'm not against this idea we'd need to ensure space is available.

2022-09-08 16:24 UTC, jordandukart commented on Homarus/src/Controller/HomarusController.php
> +            return (new BinaryFileResponse(
Think we're going to convey about this internally and look at some revisions. Thanks for taking a look @whikloj!

2022-09-14 17:48 UTC, willtp87 commented
During the tech call there was agreement in principal to continue with this approach.

2022-09-22 12:43 UTC, jordandukart commented on Homarus/src/Controller/HomarusController.php
> +            return (new BinaryFileResponse(
As discussed on the tech call we're going to document what's changing and the expectation will be the above provisioning options will need to account for this.

2022-09-22 12:44 UTC, jordandukart commented on Homarus/src/Controller/HomarusController.php
> +            ))->deleteFileAfterSend(true);
On the tech call it was discussed that given the nature of this bug maintaining backwards compatibility here isn't really desired. Similarly, while providing a separate route/controller could be an option this should be fixed for the greater community in general.

2022-09-22 22:19 UTC, whikloj commented
I think the plan is to move all the ffmpeg arguments to the islandora context like the other microservices. Just need to figure out an nice way to get them into people's context configs

2022-10-05 15:07 UTC, jordandukart approved these changes

2022-10-11 16:42 UTC, nchiasson-dgi commented
Ran tests against this PR using a large video file and it appears to perform as advertised, video file could be run immediately upon loading content display page.

2022-10-12 18:03 UTC, rosiel commented
Discussion from the Tech Call:
Merging, but... as @ruebot said we should port this to 3.x, as that's where new development should be. (Hopefully it isn't too difficult with the move of Homarus to Symfony!) Per @whikloj 's comment, If we want to move all options into config within the Drupal Actions, that's great but shouldn't block this.

2022-10-12 18:03 UTC, merged